#!/bin/bash

url=$(echo $1 | sed 's/\/$//')
url_fnc="$url/cgi-bin/cgi?req=fnc&fnc=\$\{get_json_param(ICON)\}"

charset_from='euc-jp'
charset_to='utf-8'

curl -s -X GET \
    $url_fnc | iconv -f $charset_from -t $charset_to
