#!/bin/bash

url=$(echo $1 | sed 's/\/$//')
url_top="$url/cgi-bin/cgi?req=twz"

[ -z "$url" ] && echo 'No URL is specified.' >&2 && exit 1

charset_from='euc-jp'
charset_to='utf-8'

mkdir -p node_modules
for f in jsbn prng4 rng rsa base64; do
    curl -sL "$url/js/jsbn/$f.js" > node_modules/$f.js
done

body=$(curl -s $url_top | iconv -f $charset_from -t $charset_to)
exponent=$(echo $body | grep -o 'exponent = "[0-9A-F]\+' | grep -o '[0-9A-F]\+')
modulus=$(echo $body | grep -o 'modulus = "[0-9A-F]\+' | grep -o '[0-9A-F]\+')

node encrypt.js $exponent $modulus
