#!/bin/bash

url=$(echo $1 | sed 's/\/$//')
url_wan="$url/cgi-bin/cgi?req=frm&frm=wan.html"
url_form="$url/cgi-bin/cgi?req=inp&res=wan.html"

charset_from='euc-jp'
charset_to='utf-8'

body=$(curl -s $url_wan | iconv -f $charset_from -t $charset_to | tr -d '\n')
session_num=$(echo $body | grep -o 'sWebSessionnum value=[0-9]\+' | grep -o '[0-9]\+')
session_id=$(echo $body | grep -o 'sWebSessionid value=[0-9-]\+' | grep -o '[0-9-]\+')

wan_method=$(echo $body | grep -o 'value="[0-9]\+" name="method" [^>]\+checked' | grep -o '[0-9]\+')
wan_gwaddr_4over6=$(echo $body | grep -o 'name="gwaddr_4over6"[^>]\+value="[^"]*' | grep -o 'value="[^"]*' | sed 's/value="//g')
wan_ipaddr=$(echo $body | grep -o 'name="ipaddr"[^>]\+value="[^"]*' | grep -o 'value="[^"]*' | sed 's/value="//g')
wan_netmask=$(echo $body | grep -o 'name="netmask".\+<\/select>' | grep -o ' selected>[^<]\+' | sed 's/ selected>//g')
wan_defgw=$(echo $body | grep -o 'name="defgw"[^>]\+value="[^"]*' | grep -o 'value="[^"]*' | sed 's/value="//g')
wan_dns0=$(echo $body | grep -o 'name="dns0"[^>]\+value="[^"]*' | grep -o 'value="[^"]*' | sed 's/value="//g')
wan_dns1=$(echo $body | grep -o 'name="dns1"[^>]\+value="[^"]*' | grep -o 'value="[^"]*' | sed 's/value="//g')
wan_defmac_use=$(echo $body | grep -o 'value="[0-9]\+" name="defmac_use" [^>]\+checked' | grep -o '[0-9]\+')
wan_mtu=$(echo $body | grep -o 'name="mtu"[^>]\+value="[^"]*' | grep -o 'value="[^"]*' | sed 's/value="//g')

case "$2" in
    submit)
        eval $(cat -)
        curl -s -X POST \
            --data-urlencode "method=$wan_method" \
            --data-urlencode "gwaddr_4over6=$wan_gwaddr_4over6" \
            --data-urlencode "ipaddr=$wan_ipaddr" \
            --data-urlencode "netmask=$wan_netmask" \
            --data-urlencode "defgw=$wan_defgw" \
            --data-urlencode "dns0=$wan_dns0" \
            --data-urlencode "dns1=$wan_dns1" \
            --data-urlencode "defmac_use=$wan_defmac_use" \
            --data-urlencode "mtu=$wan_mtu" \
            --data "sWebSessionnum=$session_num" \
            --data "sWebSessionid=$session_id" \
            $url_form | iconv -f $charset_from -t $charset_to >&2
        ;;
    method)
        echo $wan_method
        echo $wan_gwaddr_4over6
        echo $wan_ipaddr
        echo $wan_netmask
        ;;
    defgw)
        echo $wan_defgw
        ;;
    dns)
        echo $wan_dns0
        echo $wan_dns1
        ;;
    wan)
        echo $wan_defmac_use
        echo $wan_mtu
        ;;
    *)
        echo $wan_method
        echo $wan_gwaddr_4over6
        echo $wan_ipaddr
        echo $wan_netmask
        echo $wan_defgw
        echo $wan_dns0
        echo $wan_dns1
        echo $wan_defmac_use
        echo $wan_mtu
        ;;
esac
