#!/bin/bash

url=$(echo $1 | sed 's/\/$//')
url_logout="$url/logout.html"

[ -z "$url" ] && echo 'No URL is specified.' >&2 && exit 1

charset_from='cp932'
charset_to='utf-8'

curl -s $url_logout | iconv -f $charset_from -t $charset_to >&2
