#!/bin/bash

url=$(echo $1 | sed 's/\/$//')
url_logout="$url/cgi-bin/cgi?req=twz&frm=logout.html"

charset_from='euc-jp'
charset_to='utf-8'

curl -s $url_logout | iconv -f $charset_from -t $charset_to >&2
