#!/bin/bash

url=$(echo $1 | sed 's/\/$//')
url_init="$url/cgi-bin/cgi?req=frm&frm=save_init.html"
url_form="$url/cgi-bin/cgi?req=inp&res=waiting_page.html"

charset_from='euc-jp'
charset_to='utf-8'

body=$(curl -s $url_init | iconv -f $charset_from -t $charset_to | tr -d '\n')
session_num=$(echo $body | grep -o 'sWebSessionnum value=[0-9]\+' | grep -o '[0-9]\+' | head -1)
session_id=$(echo $body | grep -o 'sWebSessionid value=[0-9-]\+' | grep -o '[0-9-]\+' | head -1)

curl -s -X POST \
    --data-urlencode "reboot=" \
    --data-urlencode "sWebSessionnum=$session_num" \
    --data-urlencode "sWebSessionid=$session_id" \
    $url_form | iconv -f $charset_from -t $charset_to >&2
