#!/bin/bash

url=$(echo $1 | sed 's/\/$//')
url_top="$url/cgi-bin/cgi?req=twz"
url_login="$url/cgi-bin/cgi?req=inp&res=login.html"

uname='admin'
charset_from='euc-jp'
charset_to='utf-8'

body=$(curl -s $url_top | iconv -f $charset_from -t $charset_to)
session_num=$(echo $body | grep -o 'sWebSessionnum value=[0-9]\+' | grep -o '[0-9]\+')
session_id=$(echo $body | grep -o 'sWebSessionid value=[0-9-]\+' | grep -o '[0-9-]\+')
encrypted=$(cat -)

curl -s -X POST \
    --data-urlencode "airstation_uname=$uname" \
    --data-urlencode "encrypted=$encrypted" \
    --data-urlencode "sWebSessionnum=$session_num" \
    --data-urlencode "sWebSessionid=$session_id" \
    $url_login | iconv -f $charset_from -t $charset_to >&2
